@echo off

echo Checking for existing build directory...
if exist build (
    echo Removing existing build directory...
    rmdir /s /q build
)

echo checking if node_modules/smol-toml/dist/error.d.ts exists...
if exist node_modules\smol-toml\dist\error.d.ts (
    echo Patching smol-toml error.d.ts...
    powershell -Command "(Get-Content node_modules\smol-toml\dist\error.d.ts) -replace 'type TomlErrorOptions = ErrorOptions & {', 'type TomlErrorOptions = {' | Set-Content node_modules\smol-toml\dist\error.d.ts"
) else (
    echo smol-toml error.d.ts not found. Skipping patch...
)

echo Setting NODE_ENV to production...
set NODE_ENV=production

echo Compiling TypeScript files...
call tsc -p .
call tsc-alias

echo Checking for .env file...
if exist .env (
    echo Copying environment variables...
    copy .env build\.env >nul
) else (
    echo No .env file found. Skipping...
)

echo Build completed successfully.